CREATE TABLE IF NOT EXISTS ZSD_PAGECACHE_RULES (
	RULE_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	APP_ID INTEGER NOT NULL DEFAULT -1,
	URL VARCHAR(256) NOT NULL UNIQUE,
	NAME VARCHAR(64) NOT NULL DEFAULT '',
	META_XML TEXT
);

CREATE INDEX IF NOT EXISTS ZSD_PAGECACHE_RULES_IDX1 ON ZSD_PAGECACHE_RULES(APP_ID);
CREATE INDEX IF NOT EXISTS ZSD_PAGECACHE_RULES_IDX2 ON ZSD_PAGECACHE_RULES(NAME);
