INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (1, "Other", "", "");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (199, "Chrome", "", "Chrome");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (299, "Firefox", "", "Firefox");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (399, "Opera", "", "Opera");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (399, "Opera", "", "Opr");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (499, "BlackBerry", "", "BlackBerry");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (599, "Safari", "", "Safari");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (694, "IE", "10", "MSIE 10");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (695, "IE", "9", "MSIE 9");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (696, "IE", "8", "MSIE 8");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (697, "IE", "7", "MSIE 7");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (698, "IE", "6", "MSIE 6");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (699, "IE", "", "MSIE");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (799, "ApacheBench", "", "ApacheBench");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (899, "Crawlers", "", "(YandexBot|bingbot|Baiduspider|Googlebot|Bot/)");
INSERT OR IGNORE INTO stats_browsers_dictionary (id, name, version, user_agent_string) VALUES (999, "RSS", "", "(RSS|Feed)");

INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1, "Other", "", "", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (196, "Android", "4.2", "Android 4.2", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (197, "Android", "4.1", "Android 4.1", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (198, "Android", "4.0", "Android 4.0", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (199, "Android", "", "Android", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (296, "iOS", "5", "iPhone OS 5", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (297, "iOS", "4", "iPhone OS 4", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (298, "iOS", "3", "iPhone OS 3", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (299, "iOS", "", "iPhone OS", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (396, "Windows Phone", "8", "Windows Phone 8", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (397, "Windows Phone", "7.5", "Windows Phone 7.5", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (398, "Windows Phone", "7", "Windows Phone 7", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (399, "Windows Phone", "", "Windows Phone", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (499, "BlackBerry", "BlackBerry", "BlackBerry", 1);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1099, "Linux", "", "Linux", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1196, "Mac OS X", "10.7", "Mac OS X 10_7", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1197, "Mac OS X", "10.6", "Mac OS X 10_6", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1198, "Mac OS X", "10.5", "Mac OS X 10_5", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1199, "Mac OS X", "", "Mac OS X", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1287, "Windows", "8", "Windows NT 6.2", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1288, "Windows", "7", "Windows NT 6.1", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1289, "Windows", "Vista", "Windows NT 6.0", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1290, "Windows", "Server 2003", "Windows NT 5.2", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1291, "Windows", "XP", "Windows NT 5.1", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1292, "Windows", "2000, Service Pack 1 (SP1)", "Windows NT 5.01", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1293, "Windows", "2000", "Windows NT 5.0", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1294, "Windows" ,"NT 4.0", "Microsoft Windows NT 4.0", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1295, "Windows", "Me", "Windows 98 Win 9x 4.90", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1296, "Windows", "98", "Windows 98", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1297, "Windows", "95", "Windows 95", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1298, "Windows", "CE", "Windows CE", 0);
INSERT OR IGNORE INTO stats_os_dictionary (id, name, version, user_agent_string, mobile) VALUES (1299, "Windows", "", "Windows", 0);
		

INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (1, '', '');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (2, 'A1', 'Anonymous Proxy');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (3, 'A2', 'Satellite Provider');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (4, 'AD', 'Andorra');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (5, 'AE', 'United Arab Emirates');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (6, 'AF', 'Afghanistan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (7, 'AG', 'Antigua and Barbuda');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (8, 'AI', 'Anguilla');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (9, 'AL', 'Albania');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (10, 'AM', 'Armenia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (11, 'AO', 'Angola');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (12, 'AP', 'Asia/Pacific Region');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (13, 'AQ', 'Antarctica');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (14, 'AR', 'Argentina');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (15, 'AS', 'American Samoa');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (16, 'AT', 'Austria');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (17, 'AU', 'Australia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (18, 'AW', 'Aruba');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (19, 'AX', 'Aland Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (20, 'AZ', 'Azerbaijan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (21, 'BA', 'Bosnia and Herzegovina');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (22, 'BB', 'Barbados');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (23, 'BD', 'Bangladesh');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (24, 'BE', 'Belgium');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (25, 'BF', 'Burkina Faso');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (26, 'BG', 'Bulgaria');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (27, 'BH', 'Bahrain');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (28, 'BI', 'Burundi');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (29, 'BJ', 'Benin');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (30, 'BL', 'Saint Barthelemy');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (31, 'BM', 'Bermuda');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (32, 'BN', 'Brunei Darussalam');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (33, 'BO', 'Bolivia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (34, 'BQ', 'Bonaire, Saint Eustatius and Saba');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (35, 'BR', 'Brazil');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (36, 'BS', 'Bahamas');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (37, 'BT', 'Bhutan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (38, 'BW', 'Botswana');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (39, 'BY', 'Belarus');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (40, 'BZ', 'Belize');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (41, 'CA', 'Canada');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (42, 'CC', 'Cocos (Keeling) Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (43, 'CD', 'Congo, The Democratic Republic of the');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (44, 'CF', 'Central African Republic');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (45, 'CG', 'Congo');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (46, 'CH', 'Switzerland');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (47, 'CI', 'Cote D''Ivoire');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (48, 'CK', 'Cook Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (49, 'CL', 'Chile');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (50, 'CM', 'Cameroon');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (51, 'CN', 'China');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (52, 'CO', 'Colombia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (53, 'CR', 'Costa Rica');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (54, 'CU', 'Cuba');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (55, 'CV', 'Cape Verde');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (56, 'CW', 'Curacao');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (57, 'CX', 'Christmas Island');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (58, 'CY', 'Cyprus');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (59, 'CZ', 'Czech Republic');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (60, 'DE', 'Germany');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (61, 'DJ', 'Djibouti');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (62, 'DK', 'Denmark');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (63, 'DM', 'Dominica');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (64, 'DO', 'Dominican Republic');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (65, 'DZ', 'Algeria');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (66, 'EC', 'Ecuador');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (67, 'EE', 'Estonia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (68, 'EG', 'Egypt');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (69, 'EH', 'Western Sahara');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (70, 'ER', 'Eritrea');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (71, 'ES', 'Spain');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (72, 'ET', 'Ethiopia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (73, 'EU', 'Europe');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (74, 'FI', 'Finland');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (75, 'FJ', 'Fiji');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (76, 'FK', 'Falkland Islands (Malvinas)');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (77, 'FM', 'Micronesia, Federated States of');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (78, 'FO', 'Faroe Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (79, 'FR', 'France');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (80, 'GA', 'Gabon');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (81, 'GB', 'United Kingdom');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (82, 'GD', 'Grenada');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (83, 'GE', 'Georgia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (84, 'GF', 'French Guiana');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (85, 'GG', 'Guernsey');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (86, 'GH', 'Ghana');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (87, 'GI', 'Gibraltar');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (88, 'GL', 'Greenland');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (89, 'GM', 'Gambia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (90, 'GN', 'Guinea');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (91, 'GP', 'Guadeloupe');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (92, 'GQ', 'Equatorial Guinea');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (93, 'GR', 'Greece');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (94, 'GS', 'South Georgia and the South Sandwich Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (95, 'GT', 'Guatemala');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (96, 'GU', 'Guam');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (97, 'GW', 'Guinea-Bissau');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (98, 'GY', 'Guyana');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (99, 'HK', 'Hong Kong');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (100, 'HN', 'Honduras');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (101, 'HR', 'Croatia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (102, 'HT', 'Haiti');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (103, 'HU', 'Hungary');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (104, 'ID', 'Indonesia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (105, 'IE', 'Ireland');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (106, 'IL', 'Israel');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (107, 'IM', 'Isle of Man');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (108, 'IN', 'India');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (109, 'IO', 'British Indian Ocean Territory');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (110, 'IQ', 'Iraq');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (111, 'IR', 'Iran, Islamic Republic of');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (112, 'IS', 'Iceland');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (113, 'IT', 'Italy');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (114, 'JE', 'Jersey');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (115, 'JM', 'Jamaica');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (116, 'JO', 'Jordan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (117, 'JP', 'Japan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (118, 'KE', 'Kenya');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (119, 'KG', 'Kyrgyzstan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (120, 'KH', 'Cambodia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (121, 'KI', 'Kiribati');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (122, 'KM', 'Comoros');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (123, 'KN', 'Saint Kitts and Nevis');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (124, 'KP', 'Korea, Democratic People''s Republic of');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (125, 'KR', 'Korea, Republic of');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (126, 'KW', 'Kuwait');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (127, 'KY', 'Cayman Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (128, 'KZ', 'Kazakhstan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (129, 'LA', 'Lao People''s Democratic Republic');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (130, 'LB', 'Lebanon');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (131, 'LC', 'Saint Lucia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (132, 'LI', 'Liechtenstein');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (133, 'LK', 'Sri Lanka');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (134, 'LR', 'Liberia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (135, 'LS', 'Lesotho');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (136, 'LT', 'Lithuania');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (137, 'LU', 'Luxembourg');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (138, 'LV', 'Latvia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (139, 'LY', 'Libya');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (140, 'MA', 'Morocco');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (141, 'MC', 'Monaco');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (142, 'MD', 'Moldova, Republic of');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (143, 'ME', 'Montenegro');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (144, 'MF', 'Saint Martin');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (145, 'MG', 'Madagascar');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (146, 'MH', 'Marshall Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (147, 'MK', 'Macedonia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (148, 'ML', 'Mali');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (149, 'MM', 'Myanmar');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (150, 'MN', 'Mongolia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (151, 'MO', 'Macau');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (152, 'MP', 'Northern Mariana Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (153, 'MQ', 'Martinique');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (154, 'MR', 'Mauritania');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (155, 'MS', 'Montserrat');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (156, 'MT', 'Malta');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (157, 'MU', 'Mauritius');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (158, 'MV', 'Maldives');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (159, 'MW', 'Malawi');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (160, 'MX', 'Mexico');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (161, 'MY', 'Malaysia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (162, 'MZ', 'Mozambique');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (163, 'NA', 'Namibia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (164, 'NC', 'New Caledonia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (165, 'NE', 'Niger');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (166, 'NF', 'Norfolk Island');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (167, 'NG', 'Nigeria');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (168, 'NI', 'Nicaragua');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (169, 'NL', 'Netherlands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (170, 'NO', 'Norway');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (171, 'NP', 'Nepal');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (172, 'NR', 'Nauru');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (173, 'NU', 'Niue');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (174, 'NZ', 'New Zealand');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (175, 'OM', 'Oman');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (176, 'PA', 'Panama');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (177, 'PE', 'Peru');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (178, 'PF', 'French Polynesia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (179, 'PG', 'Papua New Guinea');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (180, 'PH', 'Philippines');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (181, 'PK', 'Pakistan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (182, 'PL', 'Poland');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (183, 'PM', 'Saint Pierre and Miquelon');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (184, 'PN', 'Pitcairn Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (185, 'PR', 'Puerto Rico');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (186, 'PS', 'Palestinian Territory');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (187, 'PT', 'Portugal');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (188, 'PW', 'Palau');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (189, 'PY', 'Paraguay');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (190, 'QA', 'Qatar');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (191, 'RE', 'Reunion');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (192, 'RO', 'Romania');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (193, 'RS', 'Serbia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (194, 'RU', 'Russian Federation');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (195, 'RW', 'Rwanda');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (196, 'SA', 'Saudi Arabia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (197, 'SB', 'Solomon Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (198, 'SC', 'Seychelles');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (199, 'SD', 'Sudan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (200, 'SE', 'Sweden');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (201, 'SG', 'Singapore');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (202, 'SH', 'Saint Helena');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (203, 'SI', 'Slovenia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (204, 'SJ', 'Svalbard and Jan Mayen');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (205, 'SK', 'Slovakia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (206, 'SL', 'Sierra Leone');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (207, 'SM', 'San Marino');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (208, 'SN', 'Senegal');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (209, 'SO', 'Somalia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (210, 'SR', 'Suriname');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (211, 'SS', 'South Sudan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (212, 'ST', 'Sao Tome and Principe');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (213, 'SV', 'El Salvador');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (214, 'SX', 'Sint Maarten (Dutch part)');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (215, 'SY', 'Syrian Arab Republic');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (216, 'SZ', 'Swaziland');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (217, 'TC', 'Turks and Caicos Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (218, 'TD', 'Chad');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (219, 'TF', 'French Southern Territories');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (220, 'TG', 'Togo');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (221, 'TH', 'Thailand');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (222, 'TJ', 'Tajikistan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (223, 'TK', 'Tokelau');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (224, 'TL', 'Timor-Leste');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (225, 'TM', 'Turkmenistan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (226, 'TN', 'Tunisia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (227, 'TO', 'Tonga');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (228, 'TR', 'Turkey');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (229, 'TT', 'Trinidad and Tobago');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (230, 'TV', 'Tuvalu');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (231, 'TW', 'Taiwan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (232, 'TZ', 'Tanzania, United Republic of');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (233, 'UA', 'Ukraine');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (234, 'UG', 'Uganda');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (235, 'UM', 'United States Minor Outlying Islands');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (236, 'US', 'United States');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (237, 'UY', 'Uruguay');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (238, 'UZ', 'Uzbekistan');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (239, 'VA', 'Holy See (Vatican City State)');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (240, 'VC', 'Saint Vincent and the Grenadines');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (241, 'VE', 'Venezuela');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (242, 'VG', 'Virgin Islands, British');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (243, 'VI', 'Virgin Islands, U.S.');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (244, 'VN', 'Vietnam');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (245, 'VU', 'Vanuatu');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (246, 'WF', 'Wallis and Futuna');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (247, 'WS', 'Samoa');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (248, 'YE', 'Yemen');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (249, 'YT', 'Mayotte');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (250, 'ZA', 'South Africa');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (251, 'ZM', 'Zambia');
INSERT OR IGNORE INTO stats_geo_dictionary (id, code, name) VALUES (252, 'ZW', 'Zimbabwe');
